module.exports = {
    TWILIO_AUTH_TOKEN : '',
    YELP_CLIENT_ID: '',
    YELP_CLIENT_SECRET:'',
    YELP_ACCESS_TOKEN: 'niqmDIRAiQ3MuS8NnTTI6VVjrFc86m-82aoqsgCPogfCnP4xEkJBHF-yxMWRFd75Bpv2AHah-EjJJNuCzZi1NmB6BVVmodgnYNNUyPDppzS4h8nZ4j7sU7kl0vMRWnYx'
};